name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run publish

      - name: Notify
        run: echo "Publishing by user: MD-MahfuzSarker"

      - name: Set GitHub User Name
        run: echo "Setting GitHub User Name: MD-MahfuzSarker" 

